eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.232.129:1111/eureka/,http://192.168.232.129:1112/eureka/,http://192.168.232.129:1113/eureka/
  instance:
    ip-address: 192.168.232.129
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5   # Make sure eureka server can detect whether this app is up or down. Add by Zhang Chao.
    lease-expiration-duration-in-seconds: 5